export const WINDOW_EXTENDED_TAB_CONTAINER_WIDTH = 270;
export const WINDOW_EXTENDED_SIDEBAR_WIDTH = 350;

export const WINDOW_SINGLE_LENGTH = 50;
export const WINDOW_DOUBLE_TITLE_BAR_HEIGHT = 38;
export const WINDOW_DOUBLE_TOOL_BAR_HEIGHT = 40;
